### ISSUE TITLE
netfilter: TTL commit support

### ISSUE THREAD

**Issue by Hadenix** [ramabondanp/kernel_xiaomi_mt6768#6]
**if possible, add a ttl commit to the kernel:**

[https://github.com/TheXPerienceProject/android_kernel_xiaomi_mojito/commit/2ac1ec0a9065137c54ce5975d0562a7a3a6451db](url)

**Comment by ramabondanp** [comment]
i will add it on next release

**Comment by Hadenix** [comment]
@rama982 thnk
